name: Web Build

on:
  push:
    branches:
      - 'main'

jobs:
  web-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        
      - name: Install Ionic Cloud CLI
        run: curl -sL https://ionic.io/get-ionic-cloud-cli | bash

      - name: Install project dependencies
        run: npm install

      - name: Build Web
        run: npm run build

      - name: Trigger Appflow Web Build
        run: ionic-cloud build web --app-id=b2169113 --commit=$GITHUB_SHA --token=${{ secrets.IONIC_TOKEN }}
